---
# CodeClimate config file configuration: https://docs.codeclimate.com/docs/advanced-configuration
version: "2"
plugins:
  duplication:
    enabled: true
  # ESLint: https://docs.codeclimate.com/docs/eslint
  eslint:
    enabled: true
    channel: "eslint-4"
    checks:
      complexity:
        enabled: true
    config:
      config: .eslintrc.cc.yaml
      extensions:
      - .es6
      - .js
  fixme:
    enabled: true
  # How to configure: https://docs.codeclimate.com/docs/git-legal
  git-legal:
    enabled: false
  markdownlint:
    enabled: true
    exclude_fingerprints:
    # Unavoidable lengthy lines.
    - 184efb4b1212345dcbe0bf36064230f4
    - c03f7976bb3e27eb1e08b08d0475a15b
    # Trailing question mark in heading.
    - 82098ef96fff43e6c43f874f768ef70c
    # Spaces surrounding link text (wronly reported).
    - f1d8f1048cbd287f2c5696a297926243
    # Bare URL inside contributor covenant code of conduct (automated).
    - 13fb507303344d8bd75055a4630ca70b
  # Requires a `shrinkwrap.json` at the project root to work!
  # So we'll rely on the cloud check by NodeSecurity.io.
  nodesecurity:
    enabled: false
  structure:
    enabled: true
exclude_patterns:
- ".git/**/*"
- ".nyc_output/**/*"
- ".reports/**/*"
- "coverage/**/*"
- "node_modules/**/*"
# `eslint` when exec by CodeClimate doesn't use the specific config
# file at `test/.eslintrc.yaml`, that's why we exclude it here.
- "test/**/*"
