---
  root: true
  plugins:
    - filenames
    - json
    - lodash
    - smells
    - you-dont-need-lodash-underscore
  extends:
    - airbnb-base
    - plugin:lodash/canonical
    - plugin:you-dont-need-lodash-underscore/compatible
  env:
    node: true
    browser: true
    shared-node-browser: true
  rules:
    global-require: off
    # Rules of plugin `filenames`.
    filenames/match-regex: error
    filenames/match-exported:
      - error
      - kebab
    filenames/no-index: off
    # Rules of plugin `lodash` ~> disable most of lodash preference over native rules.
    lodash/prefer-constant: error
    lodash/prefer-get: off
    lodash/prefer-includes: off
    lodash/prefer-is-nil: error
    lodash/prefer-lodash-chain: off
    lodash/prefer-lodash-method: off
    lodash/prefer-lodash-typecheck: error
    lodash/prefer-matches: off
    lodash/prefer-noop: error
    lodash/prefer-over-quantifier: off
    lodash/prefer-some: off
    lodash/prefer-startswith: off
    lodash/prefer-times: off
    # Rules of plugin `smells`
    smells/no-switch: off
    smells/no-complex-switch-case: error
    smells/no-setinterval: error
    smells/no-this-assign: error
    smells/no-complex-string-concat: error
    smells/no-complex-chaining: error
  overrides:
    - files:
        - lib/manager.js
        - test/helpers/fix.js
      rules:
        # Rules of plugin `smells` ~> Joi is meant to be chained!
        smells/no-complex-chaining: off
    - files:
        - test/**/*.spec.js
      rules:
        # Rules of plugin `smells` ~> mocha is meant to be chained!
        smells/no-complex-chaining: off
    - files:
        - bin/*.js
        - test/**/*.spec.js
      rules:
        # Rules of plugin `filenames` ~> tests/binaries export nothing!
        filenames/match-regex: 0
        filenames/match-exported: off
