---
  root: true
  plugins:
    - lodash
  extends:
    - airbnb-base
    - plugin:lodash/canonical
  env:
    node: true
    browser: true
    shared-node-browser: true
  rules:
    global-require: off
    # Rules of plugin `lodash` ~> disable most of lodash preference over native rules.
    lodash/prefer-constant: error
    lodash/prefer-get: off
    lodash/prefer-includes: off
    lodash/prefer-is-nil: error
    lodash/prefer-lodash-chain: off
    lodash/prefer-lodash-method: off
    lodash/prefer-lodash-typecheck: error
    lodash/prefer-matches: off
    lodash/prefer-noop: error
    lodash/prefer-over-quantifier: off
    lodash/prefer-some: off
    lodash/prefer-startswith: off
    lodash/prefer-times: off
