sudo: false
language: node_js
node_js:
- '8'
- '6'
cache:
  yarn: true
  directories:
  - node_modules
stages:
- test
- name: release
  if: branch = master
install:
- yarn install --ignore-engines
script:
- >
  echo "Running tests against $(node -v) ..." &&
  commitlint-travis &&
  run-p lint:* &&
  npm run test:unit &&
  npm run test:integration &&
  npm run test:functional &&
  npm run test:acceptance &&
  npm run test:coverage &&
  run-p check:*

jobs:
  include:
  - stage: release
    node_js: lts/*
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - semantic-release
env:
  global:
  - secure: cDpIk0t539zEKBy4Pcg+yLqt7nmfte+cPNPuANPZ480vX0DTRjGKL7yphRE7VNKcfG97OlQIdHhkdPu4DS72UJqCu7Dk3gJPDcYnyb9Ld5IImPh58EoB+aBeMxEr14M6DXmi9kEt5GAqX9/BWbbihGYLzNRatc4FQt1e/Kapq0OBlGcgQgCF5DuS2AgzbsdrAs/xTijCc69bEgmAXou1zlmaINLUM4g1GLOG3W3CzvgDnG2oFn1/zP/02dVxNMYoUf1ujcm3s+iCqDkzRqD/T3URC1vhhZUOlt+x1j263NSzrXNTe6zmwys/WjHqjjwrYoZRwmdAnIscdOP40HjEp/HVosoqT6HaAMDka+7IUP50xfPMOiblhw8E66u9lQ3kDoepYLpjpajYDBph/uGGBYwJY/BkoXB9zancMwt1Z3tp5yFmg2+ZPfmN0dIeq+gGfHwAc36v4aHaC/QrIpzT4WhvQDvrKfL84WTFKwc2bfxqxS8SfAeILZ+s5YUXNHLr1t39lrIz6klzuhk5CbJoQhi1B0A6ZLStQTg2skENpmauhjDGdd5sj8XlzNJ6XRkiY3hYt9qjQzGvRh9ifishTWIE9RmHG5W05bVXMUHt6FBNpj6r1aN4EdIR0f6rNr70fKQJltaYEYgxmvDdQ3tJMoacFcWo87mzzdxcYWPSJw0=
  - secure: F1Qg9N7HdYf2LQvglidjIOCEsenhGNKe87wEBc70w8HEx42fXA1fqrWlpxGjUMRbYPWOpN2ZSuXuAAmhhK8zfCofq4eTttoPFdLCivylTLcrNlRRqMN/Zg/ktf3JMOYpvaXQkVsxTJ1bfUkK0Tzl2lsrKG6iKmM6Gs40saD7s/gEWXkecBUEUIMO11RBwZrnmDtOwEzzLqzTinnewtEsoh7OfQsU+3qPJ/CxG3uYc1DRpu2j9IA/vwR8B0tt6MjSXQ/Ei3Nf1ary5maNwCl1E2ekr+nDabrjMtdnAhRkwPx5EVTOF5J1hIwMduHM7wzH8vWdnXp1K5l/K0dxY5OS4byWsBbDaHa2Evg+QqzYDRFZFSd5YldUwhyPWkc2HZVynRfbnJu37JIXFdbF9GZUH9wg6XZVwD74Q0tXZHlJ5/G6F7Xacpwf7c3GRKU8dWH/bCEMuvE0H7HifHDOmr2DdYEDnd3TEHIwRRfnpVX867j7S+liqFa88QOIIonHr0xd4TRDHjhJi7J3xC8tRHAOaqx5ygsfdWm7EfUGPSnhk6ENZYWE8TwlX9l2VZRvXZDAQ81DTIuhUkZgj8peclKLJiJ5mMrSOa50FNeQEIeZmTV8kmQkhxDwfCwWKqTqwsw+CLcGu7qeMDcrkBubFhNDYg/M6fOLWcf4jevJ6eTwW84=
